## Application Config
spring.application.name=idea_expo_backend
server.port=8081

## Database Config
spring.datasource.url=jdbc:mysql://localhost:3306/idea_expo_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root@
spring.jpa.hibernate.ddl-auto = update

## SQL
spring.jpa.show-sql=true

## Logging
logging.level.root=INFO
logging.file.name=Logs/RootLogs.log
logging.pattern.file=%d{dd-MMM-yyyy HH:mm:ss} || [%thread] || %-5level || %logger{36} || %file || %C{0} || %method || %line || %msg |||%n
logging.pattern.console=%d{dd-MMM-yyyy HH:mm:ss} - [%thread] - %-5level - %logger{36} - %file - %line - %msg%n

logging.logback.rollingpolicy.fileNamePattern=Logs/RootLogs_%d{dd-MMM-yyyy}_%i.log.gz
logging.logback.rollingpolicy.maxFileSize=100MB
logging.logback.rollingpolicy.maxHistory=30
logging.logback.rollingpolicy.totalSizeCap=5GB

