## Application Config
spring.application.name=idea_expo_backend
server.port=8081

spring.profiles.active=dev

## Logging
logging.file.name=Logs/RootLogs.log
logging.pattern.file=%d{dd-MMM-yyyy HH:mm:ss} || [%thread] || %-5level || %logger{36} || %file || %C{0} || %method || %line || %msg |||%n
logging.pattern.console=%d{dd-MMM-yyyy HH:mm:ss} - [%thread] - %-5level - %logger{36} - %file - %line - %msg%n

logging.logback.rollingpolicy.fileNamePattern=Logs/RootLogs_%d{dd-MMM-yyyy}_%i.log.gz
logging.logback.rollingpolicy.maxFileSize=100MB
logging.logback.rollingpolicy.maxHistory=30
logging.logback.rollingpolicy.totalSizeCap=5GB

